### ISSUE TITLE
wiki articles

### ISSUE THREAD

**Issue by jovo** [neurodata/neurodata.io#494]
1. open connectome project
2. biomedical data science
3. neurodata lab

@tathey1 helped get some of this started.

**Comment by asaadeldin11** [comment]
@tathey1 can you direct me to any of work you've done on this so far? Thanks!

**Comment by tathey1** [comment]
@asaadeldin11 Added you to a slack channel with this info (called #myco). There's more info there but this is the status to my knowledge:
- OCP: @mlemyco has submitted a draft for the OCP page (not sure if she got a decision back)
- Biomedical data science: a draft was submitted (not sure by who), but the response said that it is not yet suitable, mostly because it needs citations from reliable independent sources.

**Comment by asaadeldin11** [comment]
open connectome project [page](https://en.wikipedia.org/wiki/Draft:Open_Connectome_Project) resubmitted

**Comment by jshinm** [comment]
Continued on #556
